/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   temperature_sensor__init
                     (TemperatureSensor         *message)
{
  static const TemperatureSensor init_value = TEMPERATURE_SENSOR__INIT;
  *message = init_value;
}
size_t temperature_sensor__get_packed_size
                     (const TemperatureSensor *message)
{
  assert(message->base.descriptor == &temperature_sensor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t temperature_sensor__pack
                     (const TemperatureSensor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &temperature_sensor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t temperature_sensor__pack_to_buffer
                     (const TemperatureSensor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &temperature_sensor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TemperatureSensor *
       temperature_sensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TemperatureSensor *)
     protobuf_c_message_unpack (&temperature_sensor__descriptor,
                                allocator, len, data);
}
void   temperature_sensor__free_unpacked
                     (TemperatureSensor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &temperature_sensor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor temperature_sensor__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TemperatureSensor, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(TemperatureSensor, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned temperature_sensor__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = temperature */
};
static const ProtobufCIntRange temperature_sensor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor temperature_sensor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TemperatureSensor",
  "TemperatureSensor",
  "TemperatureSensor",
  "",
  sizeof(TemperatureSensor),
  2,
  temperature_sensor__field_descriptors,
  temperature_sensor__field_indices_by_name,
  1,  temperature_sensor__number_ranges,
  (ProtobufCMessageInit) temperature_sensor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
