/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */
/* Note this file has been included in the test resources to avoid having to install and configure protobuf-c just for
 * testing purposes. */

#ifndef PROTOBUF_C_messages_2eproto__INCLUDED
#define PROTOBUF_C_messages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct TemperatureSensor TemperatureSensor;


/* --- enums --- */


/* --- messages --- */

struct  TemperatureSensor
{
  ProtobufCMessage base;
  char *id;
  float temperature;
};
#define TEMPERATURE_SENSOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&temperature_sensor__descriptor) \
, (char *)protobuf_c_empty_string, 0 }


/* TemperatureSensor methods */
void   temperature_sensor__init
                     (TemperatureSensor         *message);
size_t temperature_sensor__get_packed_size
                     (const TemperatureSensor   *message);
size_t temperature_sensor__pack
                     (const TemperatureSensor   *message,
                      uint8_t             *out);
size_t temperature_sensor__pack_to_buffer
                     (const TemperatureSensor   *message,
                      ProtobufCBuffer     *buffer);
TemperatureSensor *
       temperature_sensor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   temperature_sensor__free_unpacked
                     (TemperatureSensor *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TemperatureSensor_Closure)
                 (const TemperatureSensor *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor temperature_sensor__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_2eproto__INCLUDED */
