FROM sbtscala/scala-sbt:eclipse-temurin-25_36_1.11.7_3.7.3

RUN apt-get update && \
    apt-get install -y llvm-17 clang-17 && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/usr/lib/llvm-17/bin:${PATH}"

WORKDIR /project
