// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file foo.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file foo.proto.
 */
export const file_foo: GenFile = /*@__PURE__*/
  fileDesc("Cglmb28ucHJvdG8iHwoDRm9vEgwKBG5hbWUYASABKAkSCgoCaWQYAiABKAViBnByb3RvMw");

/**
 * @generated from message Foo
 */
export type Foo = Message<"Foo"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 id = 2;
   */
  id: number;
};

/**
 * Describes the message Foo.
 * Use `create(FooSchema)` to create a new message.
 */
export const FooSchema: GenMessage<Foo> = /*@__PURE__*/
  messageDesc(file_foo, 0);

